# Generated by Django 4.2.21 on 2025-06-07 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0004_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre',
        ),
        migrations.CreateModel(
            name='SongGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunaapi.genre')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tunaapi.song')),
            ],
            options={
                'db_table': 'song_genre',
            },
        ),
    ]
